### ISSUE TITLE
Add capability to track special holiday events.

### ISSUE THREAD

**Issue by chancedj** [chancedj/LockedOut#107]
Winter Veil, Halloween, etc.  These are all special events that will need a framework implemented.

**Comment by chancedj** [comment]
This will go together with #93

**Comment by chancedj** [comment]
looking to get an initial list of the holidays people want tracked.  I know the christmas and halloween.  What are the other major ones?

**Comment by Daeveren** [comment]
Leaving the full list here, in order to be discussed http://www.wowhead.com/holidays
I believe people would want to track the one time per event quests or daily quests inside the relevant events.
If that's the case, then I guess we should start putting together relevant daily quests for each event.
Also, since the world events repeat on the same date every year (sometimes they get delayed, if needed to not overlap with an expansion release), or if the corresponding date/period can be called ingame by some kind of functions, then I suppose the addon should automatically list in its tooltip something like: Currently the active world event is: NAME OF THE EVENT (date/period active); and then list each of the relevant quests/dailies by default, followed by a checkmark if the player completes them.

Maybe something like this?
![2018-05-12 12_18_18-window](https://user-images.githubusercontent.com/6321337/39955850-baa04a0a-55de-11e8-9a87-1beab97cd195.jpg)

Also, if possible, there would be a setting for something like "display the upcoming world event in advance", where the event with its quest would show with X days in advance (where X would probably be a selectable value like 1,5,10).

**Comment by chancedj** [comment]
Great! thanks.  will look into this for either 1.9 or 1.10.  pretty soon i'll have to stop work and work on the new BFA changes.  but it sounds like they won't be that bad initially.

1.9 will help to make this change better as i should be able to enable the "placeholder" items for when a quest is available but you haven't completed.  that way you can see what things you need to do that day.

**Comment by chancedj** [comment]
this and #93 will be completed together.
