### ISSUE TITLE
caching of characters data

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#39]
Add some sort of caching for characters data so that the database doesn't wipe with each addon update. Atleast this is what I've noticed, every time I update LockedOut, I have to log again on each of my chars in order to have the data populate.

**Comment by chancedj** [comment]
this shouldn't be happening.  last update i only changed the map variable from character to account wide because i changed it to save the minimap data.  it should only be wiping out all the char data when the lockouts expire.  even though all characters have currencies, it doesn't display the character unless there is a world boss, instance or raid lockout.

This will likely change once i get the emissaries added as then it should always show data.  I'll keep an eye on this though, thanks for bringing it up

**Comment by Daeveren** [comment]
Well, I could reproduce this just now.
1st screenshot I took as I was reading your comment and then I've logged on my DK too and took the 2nd screenshot. 1st one doesn't have the DK even though he had the lockouts for 2 world bosses and the TBC Karazhan raid and I've always had the LockedOut addon enabled. So most likely latest version changed something.

![2017-09-30 17_56_32-world of warcraft](https://user-images.githubusercontent.com/6321337/31046865-48d87b7a-a609-11e7-9cc6-f916394a1509.jpg)

![2017-09-30 17_57_46-world of warcraft](https://user-images.githubusercontent.com/6321337/31046867-4cae60ac-a609-11e7-99a1-9f7b2e4264d6.jpg)

**Comment by chancedj** [comment]
Ok.  I'm pretty sure I know what's happening here.  Look at issue #17 ... I think you are hovering over the icon before the client is fully ready.  When this happens it wipes out the current characters data because I rebuild it on the fly.  Once #17 is done this won't happen anymore.  I'll leave it open until #17 is closed.

**Comment by Daeveren** [comment]
No it's not that. 1st pic was taken while logged on one of my mages I believe, the thing is that the DK was not showing at all in the tooltip (despite the DK having LockedOut addon when he got the kills). When I've logged in the DK, he showed up in the list again. Just now I've logged on my hunter and now he shows up in the list, but it didn't before (even tho he had LockedOut always loaded for the past weeks, including when he got the kills/lockouts).

![2017-09-30 18_54_19-world of warcraft](https://user-images.githubusercontent.com/6321337/31047317-f6bca5c0-a610-11e7-8daa-dfa42d634e1f.jpg)

**Comment by chancedj** [comment]
ok, thanks.  What are the names like (don't need the name or realm, just an example).

Do you name the chars the same on all realms you plan?

**Realm 1 - somename1**
Realm 1 - somename2
**Realm 2 - somename1**
Realm 2 - somename3

Just trying to nail down a scenario that i can test on my end.

**Comment by Daeveren** [comment]
I have no chars with the same name on different realms, all of them have unique names.

**Comment by chancedj** [comment]
ok, thanks.  just trying to get as much data as i can before looking into it.

**Comment by chancedj** [comment]
give the latest push a shot.  it's possible that that has now corrected the issue.
